### ISSUE TITLE
Is the miniLock-encryption secure?

### ISSUE THREAD

**Issue by mrossk** [kaepora/miniLock#180]
Hello.

A (part of a) miniLock-ID is used to encrypt the files. Such a miniLock-ID is 45 bytes long. 45 bytes are 360 bit.

MiniLock uses asymmetric encryption. RSA (which also uses asymmetric encryption) should have 2048 bit (recommended by german BSI), better 3072 bit (recommended by Snowden I have read somewhere) otherwise it is much more weak than symmetric encryption like AES-128. But 360 bit and 2048/3072 bit is a big difference.

So, is miniLock really secure? Does it use another way to en-/decrypt the files so the 45 bytes long miniLock-ID is secure enough in this case? I am not a specialist but the 45 bytes seem very short to me for an asymmetric encryption.

When I use encryption then I want to be sure that it is really secure.

Thank you for an explanation.

Marcel.

**Comment by SparkDustJoe** [comment]
Hi Marcel,

You're not comparing apples-to-apples with RSA and Curve25519 encryption.  Curve25519 is Elliptic Curve cryptography, which achieves a greater security per bit than RSA.  Also, the key is 32 bytes encoded to 45 characters.  Curve25519 is widely deployed and generally considered secure by the community.

https://en.wikipedia.org/wiki/Curve25519
http://cr.yp.to/ecdh.html

-Dustin

**Comment by mrossk** [comment]
Thank you for your answer and the links. Now I trust this great and simple to use program!

**Comment by kaepora** [comment]
:-)
