### ISSUE TITLE
[Question] miniLock-based key for signing?

### ISSUE THREAD

**Issue by elimisteve** [kaepora/miniLock#198]
I love miniLock's properties of being able to efficiently encrypt data to multiple people as well as hide the sender and recipients, but I really need to be able to cryptographically sign data without also encrypting it.

It appears that it's not possible to just sign (and not encrypt) with miniLock, but is there some way I could somehow extract a key that I _can_ use for signing from miniLock's underlying EC code?

Thanks!

**Comment by SparkDustJoe** [comment]
The secret key is calculated from the user's email address and password, but only kept in memory.  At the point where encryption begins and the header is being built, the secret is used to "twist" with the Ephemeral key and the Recipient keys.  If you follow the same initialization steps, you can generate the miniLock key pairs outside of miniLock pretty easily.

Look here under Initialize:  https://github.com/SparkDustJoe/miniLockManaged/blob/master/miniLockManaged/Keys.cs 
for guidance.

**Comment by elimisteve** [comment]
This sounds like a very viable option for me, @SparkDustJoe, thanks!

**Comment by SparkDustJoe** [comment]
I vote to close this issue.

**Comment by elimisteve** [comment]
@SparkDustJoe :+1:
