### ISSUE TITLE
SSL cert error on https://www.minilock.io

### ISSUE THREAD

**Issue by geekafy** [kaepora/miniLock#204]
Hi guys,

Just wanted to tell you that there is a SSL cert error when we go on the HTTPS version of the site:

minilock.io uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by Fastidious** [comment]
Everyone knows. Sadly, miniLock seems to be abandonware. The domain itself, minilock.io, is no longer under Nadim control.
