### ISSUE TITLE
minilock.io was hacked

### ISSUE THREAD

**Issue by adakaleh** [kaepora/miniLock#213]
https://www.minilock.io/ has been compromised by spammers, see:

> Service miniLock uses the formation of quotas for animal insurance. This is safe and secure. The first project to implement this technology was SPAM-URL.

Please also check https://minilock.org/, is it still trustworthy?

**Comment by SparkDustJoe** [comment]
This project has been dormant for some time, likely Nadim did not renew the
domain and it has been bought up by someone else. DO NOT TRUST.

**Comment by kaepora** [comment]
Not sure what's going on here, nothing was hacked. The domain name expired. I'll remove it from the README.

This project is obviously abandoned.
